/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'ilsasdo' at '04/10/16 8.39' with Gradle 2.6
 *
 * @author ilsasdo, @date 04/10/16 8.39
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
